# Assignment 1

# MAS DSE200

## Instructions

* The answers to the questions should be submitted on github. 
* You don’t need to explain your approach (unless specified) so please be concise in your submission. 
* To obtain full marks for a question, both the answer and the code should be correct. 
* Completely wrong (or missing) code with correct answer will result in zero marks. 
* Please code the solution in the space provided.

# Part 1: Python

**1.1**:  Write a program to swap 2 variables and print their data types

* Initialize 2 variables my_int = 5 , and my_float = 1.5
* Swap these variables such that my_int now holds the value of my_float and vice versa
* Verify this by printing their data types 

In [1]:
# COMPLETE THE CELL BELOW 

my_int = 5
my_float = 1.5

temp = my_int
my_int = my_float
my_float = temp

print ("Value of my_int = ", my_int)
print ("Data type of my_int = ", type(my_int))
print ("Value of my_float = ",my_float)
print ("Data type of my_float = ", type(my_float))

Value of my_int =  1.5
Data type of my_int =  <class 'float'>
Value of my_float =  5
Data type of my_float =  <class 'int'>


**1.2**  Write a Python Program to Calculate the Area of a Triangle

* Initialize the 3 sides of the triangle a, b and c to 5, 6 and 7 
* Calculate the semiperimeter using the formula - s = (a+b+c)/2
* Calculate the area using the formula - area = √(s(s-a)*(s-b)*(s-c))

In [2]:
# COMPLETE THE CELL BELOW 

a = 5
b = 6
c = 7

s = (a+b+c)/2 # calculate the semi-perimeter
area = (s*(s-a)*(s-b)*(s-c))**0.5  # calculate the area

print('The area of the triangle is %0.2f' %area)

The area of the triangle is 14.70


**1.3**: Write a Python Program to Check if a Number is Odd or Even

* Initialize a variable that takes input from user
* Check and print if the number is odd or even

In [3]:
# COMPLETE CELL BELOW

num = 8# Enter a number
if num%2 == 0:
    print("Number is even")
else:
    print("Number is odd")

Number is even


**1.4**: Write a Python Program to Check Whether a String is Palindrome or Not

* Initialize a string
* Lower case it to allow easy comparison
* Check using if-else statements if the string is a palindrome 
* A palindrome is a string which is same read forward or backwards.

In [4]:
# COMPLETE CELL BELOW 

my_str = 'palindrome' # change this value for a different output

my_str = my_str.lower()
if my_str == my_str[::-1]:
    print ("String is a palindrome")
else:
    print ("String is not a palindrome")

String is not a palindrome


**1.6**  **Print numbers divisible by 3 between 1 and 20, inclusive**

* Take upper limit 20 using range
* Iterate through these numbers using for loop
* Print only a number divisible by 3 using if

In [5]:
# COMPLETE THE CELL BELOW 

limit = range(20)
for number in limit: # Complete the loop
    if number%3 == 0:
        print(number)

0
3
6
9
12
15
18


**1.7** Write a Python Program to print the following pattern

* Initialize a variable n that denotes the number of lines
* Use nested for loops to print the following pattern 

1<br>
1 2<br>
1 2 3<br> 
1 2 3 4<br> 
1 2 3 4 5<br> 

In [6]:
# COMPLETE CELL BELOW

n = 5 
for i in range(0, n): 
        num = 1
        for j in range(0, i+1): 
            print(num, end=" ") 
            num = num + 1
        print("\r") 

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [7]:


# COMPLETE CELL BELOW

n = 5 
for number in range(1,n+1):
    print(*range(1,number+1)) #print without a quotation/bracket



1
1 2
1 2 3
1 2 3 4
1 2 3 4 5


### 1.8 Write a Python Program that defines a function to Remove Punctuations From a String

* You can initialize a string of your choice 
* Define the function 
* Use a for loop to remove punctuations

In [8]:
# COMPLETE THE CELL BELOW 

punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~''' 

def removePunc(s): 

    no_punct = ""
    for char in my_str:
        if char not in punctuations:
               no_punct = no_punct + char
    return no_punct

my_str = "Hello!!!, he said ---and went."
print (removePunc(my_str))

Hello he said and went


In [9]:
# OR use a list comprehension 

def removePunc(s): 
    return ''.join([c for c in s if c not in punctuations])


my_str = "Hello!!!, he said ---and went."
print (removePunc(my_str))

Hello he said and went


### 1.9 **Write a program to define a function that takes a limit as a parameter and returns the sum of all numbers upto that limit (exclusive)**

* You can define a limit of your choice 
* Define the function 
* Use a for loop to add numbers upto the limit

In [10]:
# COMPLETE THE CELL BELOW 

def sum(limit): # Complete the function using a for loop and range
    total = 0
    for i in range(limit):
        total += i
    return total
limit = 5 # Define a limit of your choice 
total = sum(limit)
print ("Result is", total)

Result is 10


### 1.10 Define a class named Rectangle that can calculate the area

* The class can be constructed by a length and width
* The class has a method which can compute the area 

In [11]:
# COMPLETE CELL BELOW 

class Rectangle(object):
    def __init__(self, l, w):
        self.length = l
        self.width = w
        
    def area(self):
        return self.length * self.width
    
rect_obj = Rectangle(5,2)

print("Areaof rectangle is ", rect_obj.area())

Areaof rectangle is  10


# Part 2: Numpy

### Data

Download the `wine_data.csv` and `wine_modified.csv` data from tritoned and place the file in the same folder as this jupyter notebook.

In [5]:
import numpy as np

raw_data = np.genfromtxt('./wine_data.csv', delimiter=',')[1:]

**2.1**: Write code to find out how many unique classes are there in the dataset.

In [6]:
np.unique(raw_data[:, -1])

array([1., 2., 3.])

**2.2**: Calculate the row-wise sum of the data.

In [7]:
raw_data.sum(axis=1)

array([ 671.31    ,  614.91    , 1461.      ,  428.88    , 1671.6     ,
        570.3     ,  869.35    ,  666.42    ,  625.29    ,  527.67    ,
       1142.64    , 1292.52    ,  878.19    ,  631.12    ,  643.34    ,
        519.77    ,  659.51    ,  505.84    , 1702.52    ,  720.6     ,
       1302.79    ,  589.55    ,  630.72    ,  608.74    , 1445.95    ,
       1437.46    ,  611.059999, 1044.5     ,  966.36    , 1355.12    ,
        827.59    , 1197.46    , 1616.23    ,  525.59    ,  927.08    ,
        832.4     , 1248.08    ,  597.72    ,  700.57    ,  809.24    ,
        524.49    ,  656.85    ,  458.7     ,  762.32    , 1413.44    ,
        560.86    ,  827.85    ,  547.32    ,  723.56    ,  761.33    ,
       1139.88    ,  413.33    ,  601.6     , 1428.11    , 1469.78    ,
        697.57    ,  799.59    ,  714.3     ,  543.88    ,  498.54    ,
       1021.236   , 1039.27    ,  747.92    ,  841.02    ,  673.33    ,
        507.9     ,  915.92    , 1677.79    ,  921.95    , 1293.

**2.3**: Calculate the column-wise mean of the data.

In [8]:
raw_data.mean(axis=0)

array([1.29517000e+01, 2.36250000e+00, 2.32670000e+00, 1.93720000e+01,
       9.80500000e+01, 2.25280000e+00, 1.98770000e+00, 3.68700000e-01,
       1.59900000e+00, 4.99539999e+00, 9.73760000e-01, 2.60500000e+00,
       7.17770000e+02, 1.94000000e+00])

**2.4**: Calculate the class-wise mean and standard deviation of the each column.

In [9]:
## SOLUTION 4
print("Class 1: ")
print("\tMean: ", raw_data[raw_data[:, -1] == 1].mean(axis=0))
print("\tSTD: ", raw_data[raw_data[:, -1] == 1].std(axis=0))

print("\nClass 2: ")
print("\tMean: ", raw_data[raw_data[:, -1] == 2].mean(axis=0))
print("\tSTD: ", raw_data[raw_data[:, -1] == 2].std(axis=0))

print("\nClass 3: ")
print("\tMean: ", raw_data[raw_data[:, -1] == 3].mean(axis=0))
print("\tSTD: ", raw_data[raw_data[:, -1] == 3].std(axis=0))

Class 1: 
	Mean:  [1.37835484e+01 1.99774194e+00 2.43225806e+00 1.69645161e+01
 1.05967742e+02 2.87806452e+00 3.01935484e+00 2.90000000e-01
 2.00193548e+00 5.72774194e+00 1.06290323e+00 3.17129032e+00
 1.12425806e+03 1.00000000e+00]
	STD:  [4.83458964e-01 6.73032184e-01 2.43730545e-01 3.22085426e+00
 1.03065400e+01 3.07523084e-01 3.90036685e-01 7.02529990e-02
 4.26224379e-01 1.19693347e+00 1.04517125e-01 3.11994023e-01
 2.33113010e+02 0.00000000e+00]

Class 2: 
	Mean:  [1.22415909e+01 2.10977273e+00 2.18863636e+00 1.97909091e+01
 9.16136364e+01 2.15227273e+00 1.93113636e+00 3.81136364e-01
 1.55863636e+00 2.99909091e+00 1.07331818e+00 2.72613636e+00
 4.85681818e+02 2.00000000e+00]
	STD:  [4.80562848e-01 1.16372929e+00 2.97684938e-01 2.99369171e+00
 1.29828837e+01 4.73112824e-01 5.66441106e-01 1.23052389e-01
 6.10962694e-01 9.87360619e-01 2.23113890e-01 5.19589943e-01
 1.30644168e+02 0.00000000e+00]

Class 3: 
	Mean:  [1.31700000e+01 3.25960000e+00 2.43880000e+00 2.16200000e+01
 9.956000

Use `wine_modified.csv` for the following questions.

In [13]:
import numpy as np
raw_data = np.genfromtxt('./wine_modified.csv', delimiter=',')[1:]


**2.5** (optional): Remove the rows with missing labels (’class’) and rows with more than 7 missing features. Report the remaining number of rows.

In [15]:

columns = open('./wine_modified.csv', 'r').readline().strip().split(',')


## SOLUTION 5
print(raw_data.shape)
classes_filter_data = raw_data[~np.isnan(raw_data[:,-1])]
print(raw_data.shape)
filtered_data = classes_filter_data[np.count_nonzero(np.isnan(classes_filter_data),axis=1) < 7 ]
print(filtered_data.shape)



(178, 14)
(168, 14)
(163, 14)


In [23]:
# Get columns
columns = open('./wine_modified.csv', 'r').readline().strip().split(',')

print(len(raw_data))

# remove the rows with more than 7 missing features
raw_data = raw_data[np.isnan(raw_data).sum(axis=1)<=7]
print(len(raw_data))

# remove the rows with missing labels
raw_data = raw_data[~np.isnan(raw_data[:, columns.index('class')])]
print(raw_data.shape)

# get the number of rows
raw_data.shape[0]

178
163
(154, 14)


154

In [4]:
import numpy as np
np.isnan

<ufunc 'isnan'>

**2.6** (optional): Remove features with >50% of missing values. For other features with missing values fill them with the mean of the corresponding features. Report the removed features (if any) and standard deviation of features with missing values after filling.

In [24]:
## SOLUTION 6
#raw_data = np.genfromtxt('./wine_modified.csv', delimiter=',')[1:]

# get columns with > 50% missing values
remove_columns = np.where(np.isnan(raw_data).sum(axis=0) > (raw_data.shape[0] / 2))[0]
print("Removed columns: ", remove_columns)
print("Removed features: ", [columns[i] for i in remove_columns])

# bookkeeping
for column in remove_columns:
    del columns[column]

# remove those columns
raw_data = np.delete(raw_data, remove_columns, axis=1)

# get column with missing values
null_columns = np.where(np.isnan(raw_data).sum(axis=0) > 0)[0]

# Obtain mean of columns as you need, nanmean is just convenient, ignores NaN
col_mean = np.nanmean(raw_data, axis=0)

# Find indices that you need to replace
inds = np.where(np.isnan(raw_data))

# Place column means in the indices. Align the arrays using take
raw_data[inds] = np.take(col_mean, inds[1])

for i in null_columns:
    print("Standard deviation for feature (", columns[i], "): ", raw_data[:, i].std(axis=0))


Removed columns:  [3]
Removed features:  ['Ash']
Standard deviation for feature ( Magnesium ):  14.393416666995842
Standard deviation for feature ( Flavanoids ):  0.8707323233936536


**2.7** (optional): Detect and remove rows with any outliers/incorrect values in features ’alcohol’ and ’proline’ (if any). Clearly state the basis of your removal in comments.

In [20]:
## SOLUTION 7

# get feature indices
features = np.array([columns.index(feat_name) for feat_name in ['Alcohol', 'Proline']])

# get mean and std for columns
mu = np.mean(raw_data[:, features], axis=0), 
sigma = np.std(raw_data[:, features], axis=0, ddof=1)

# remove rows with outliers
raw_data = raw_data[np.all(np.abs((raw_data[:, features] - mu) / sigma) < 1, axis=1)]#.shape

In [21]:
print(raw_data)
print(raw_data.shape)

[[1.000e+00 1.324e+01 2.590e+00 ... 1.040e+00 2.930e+00 7.350e+02]
 [1.000e+00 1.364e+01 3.100e+00 ... 9.600e-01 3.360e+00 8.450e+02]
 [1.000e+00 1.406e+01 1.630e+00 ... 1.090e+00 3.710e+00 7.800e+02]
 ...
 [3.000e+00 1.327e+01 4.280e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [3.000e+00 1.317e+01 2.590e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [3.000e+00 1.413e+01 4.100e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
(98, 13)


In [26]:
s = 'hello'
s[-1::-1]

'olleh'